### ISSUE TITLE
Connection failure exception not caught properly on OS X (possibly *nix)

### ISSUE THREAD

**Issue by jlnr** [bil-bas/wrath#36]
Yo:

```
#<Timeout::Error: execution expired>
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:114:in `initialize'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:114:in `new'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:114:in `block in connect'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:113:in `connect'
/Users/jlnr/Desktop/wrath/lib/wrath/states/client.rb:18:in `block in initialize'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:145:in `call'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:145:in `block in update_trait'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:144:in `each'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:144:in `update_trait'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_state_manager.rb:279:in `update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/window.rb:144:in `intermediate_update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/window.rb:112:in `update'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:128:in `update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/gosu-0.7.29-universal-darwin/lib/gosu/swig_patches.rb:10:in `update_'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:151:in `show'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:151:in `run'
bin/wrath.rbw:39:in `<main>'
ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:113:in `connect'
/Users/jlnr/Desktop/wrath/lib/wrath/states/client.rb:18:in `block in initialize'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:145:in `call'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:145:in `block in update_trait'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:144:in `each'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:144:in `update_trait'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_state_manager.rb:279:in `update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/window.rb:144:in `intermediate_update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/window.rb:112:in `update'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:128:in `update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/gosu-0.7.29-universal-darwin/lib/gosu/swig_patches.rb:10:in `update_'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:151:in `show'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:151:in `run'
bin/wrath.rbw:39:in `<main>'
FATAL ERROR - Timeout::Error: execution expired
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:114:in `initialize'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:114:in `new'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:114:in `block in connect'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_states/network_client.rb:113:in `connect'
/Users/jlnr/Desktop/wrath/lib/wrath/states/client.rb:18:in `block in initialize'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:145:in `call'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:145:in `block in update_trait'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:144:in `each'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/traits/timer.rb:144:in `update_trait'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/game_state_manager.rb:279:in `update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/window.rb:144:in `intermediate_update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/chingu-0.9rc4/lib/chingu/window.rb:112:in `update'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:128:in `update'
/Users/jlnr/.rvm/gems/ruby-1.9.2-p180/gems/gosu-0.7.29-universal-darwin/lib/gosu/swig_patches.rb:10:in `update_'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:151:in `show'
/Users/jlnr/Desktop/wrath/lib/wrath/game.rb:151:in `run'
bin/wrath.rbw:39:in `<main>'
```

**Comment by bil-bas** [comment]
Previously catching Timeout (a module) but should catch Timeout::Error (the exception). Monkey-patched in Wrath, rather than fixed the underlying code. Pushed - can you double check that works now please?
